### ISSUE TITLE
File master/adc.c: 'channels' array possible index out of bound error

### ISSUE THREAD

**Issue by VladUA** [Dandi91/master#1]
Hi Aleksandr,

I have to use SDADC in STM32F373 MCU and STM's software libray.
The SDADC_GetInjectedConversionValue function will return constant from scope SDADC_Channel_x to &channel pointed variable.

As we will see in stm32f37x_sdadc.h file:
# define SDADC_Channel_0                              ((uint32_t)0x00000001)
# define SDADC_Channel_1                              ((uint32_t)0x00010002)
# define SDADC_Channel_2                              ((uint32_t)0x00020004)
# define SDADC_Channel_3                              ((uint32_t)0x00030008)
# define SDADC_Channel_4                              ((uint32_t)0x00040010)
# define SDADC_Channel_5                              ((uint32_t)0x00050020)
# define SDADC_Channel_6                              ((uint32_t)0x00060040)
# define SDADC_Channel_7                              ((uint32_t)0x00070080)
# define SDADC_Channel_8                              ((uint32_t)0x00080100)

So, 'channels' array index out of your bound 0-8 for all channels except zero channel which reflect to first array element.

I wrote simple construction to use SDADC_GetInjectedConversionValue function:

   val = SDADC_GetInjectedConversionValue( SDADC1, &channel );
   switch( channel )
    {
     case SDADC_Channel_4:  accel_raw_x[ accel_adc_index ] = val - OffsetX; break;
     case SDADC_Channel_8:  accel_raw_y[ accel_adc_index ] = val - OffsetY; break;
     default: error++;
    }

Are you tested your code at this point? Please check it for next time.

**Comment by Dandi91** [comment]
Hi, Vlad!

I'm really sorry for misunderstanding, but this code has never been tested and will never be tested. It only meant to be look like code and be compiled, nothing more.
The only part that actually was tested is RFT module code for MRF49XA in SPI_Lib. But none of the rest of the code was ever loaded into MCU.

I will add a readme file to warn others in case somebody would want to use it, which I highly don't recommend. I haven't done it before just because I thought nobody would ever look at it.

But anyways thank you for pointing out my mistake. I appreciate that.

**Comment by VladUA** [comment]
Hi Aleksandr,

Even if it is not your mistake, please note at the possible problems for peoples who use this source code.
We have the problem with array index out of defined bound.

Channels array definition (file adc.c, line 3):
uint16_t channels[8];

But here (file adc.c, lines 17-18) program use channel variable as array index:
result = SDADC_GetInjectedConversionValue(SDADC1,&channel);
channels[channel] = result;

Array index variable (channel) will be set in SDADC_GetInjectedConversionValue to one of list:
0x00000001
0x00010002
0x00020004
0x00030008
0x00040010
0x00050020
0x00060040
0x00070080
0x00080100

So, at line 18 program will try to write to.. channels[524544] = result;
Oops.. this code cannot run without modification.

I found this source, using Google, when to do real work programming multi-channel ADC. Other people may also try to use this code as working.

**Comment by Dandi91** [comment]
Thank you again, Vlad. 

The error is mine and I will fix it as soon as I have time. I already wrote a warning message for those who would like to use this code as is.

I didn't think about consequences of making this code public, which is probably a bigger mistake than the one in the code. At least, I should have written a warning.

**Comment by VladUA** [comment]
Thank you Aleksandr!
